2022-01-24 17:31:33,724 - files.py - write 928 bytes to './final_exemplars/S5_length_tests/immunogenic_glycans_max/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2022-01-24 17:31:33,724 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2022-01-24 17:31:34,311 - files.py - write 4523 bytes to './final_exemplars/S5_length_tests/immunogenic_glycans_max/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2022-01-24 17:31:34,312 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2022-01-24 17:31:34,668 - files.py - write 30516 bytes to './final_exemplars/S5_length_tests/immunogenic_glycans_max/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2022-01-24 17:31:34,668 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2022-01-25 00:10:29,509 - connectionpool.py - Starting new HTTPS connection (1): pypi.org:443
2022-01-25 00:10:29,661 - connectionpool.py - https://pypi.org:443 "GET /pypi/tpot/json HTTP/1.1" 301 212
2022-01-25 00:10:29,698 - connectionpool.py - https://pypi.org:443 "GET /pypi/TPOT/json HTTP/1.1" 200 11943
2022-01-25 00:12:52,087 - utils.py - Code block execution exceeded 10 seconds timeout
Traceback (most recent call last):
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/stopit/utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/tpot/decorators.py", line 57, in time_limited_call
    func(*args)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/pipeline.py", line 335, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/core.py", line 436, in inner_f
    return f(**kwargs)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/sklearn.py", line 1187, in fit
    callbacks=callbacks,
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/training.py", line 197, in train
    early_stopping_rounds=early_stopping_rounds)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/training.py", line 81, in _train_internal
    bst.update(dtrain, i, obj)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/core.py", line 1501, in update
    dtrain.handle))
stopit.utils.TimeoutException
2022-01-25 00:14:46,614 - utils.py - Code block execution exceeded 10 seconds timeout
Traceback (most recent call last):
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/stopit/utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/tpot/decorators.py", line 57, in time_limited_call
    func(*args)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/pipeline.py", line 335, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/ensemble/_gb.py", line 500, in fit
    sample_weight_val, begin_at_stage, monitor, X_idx_sorted)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/ensemble/_gb.py", line 557, in _fit_stages
    random_state, X_idx_sorted, X_csc, X_csr)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/ensemble/_gb.py", line 212, in _fit_stage
    check_input=False, X_idx_sorted=X_idx_sorted)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/tree/_classes.py", line 1246, in fit
    X_idx_sorted=X_idx_sorted)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/tree/_classes.py", line 375, in fit
    builder.build(self.tree_, X, y, sample_weight, X_idx_sorted)
stopit.utils.TimeoutException
