2023-01-22 15:30:08,971 - files.py - write 911 bytes to './exemplars/augmentation_tests/toeholds_small_rev_aug/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2023-01-22 15:30:08,971 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2023-01-22 15:30:09,584 - files.py - write 4424 bytes to './exemplars/augmentation_tests/toeholds_small_rev_aug/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2023-01-22 15:30:09,585 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2023-01-22 15:30:09,944 - files.py - write 30160 bytes to './exemplars/augmentation_tests/toeholds_small_rev_aug/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2023-01-22 15:30:09,945 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2023-01-22 18:19:02,677 - connectionpool.py - Starting new HTTPS connection (1): pypi.org:443
2023-01-22 18:19:03,050 - connectionpool.py - https://pypi.org:443 "GET /pypi/tpot/json HTTP/1.1" 200 12517
2023-01-22 18:45:27,116 - utils.py - Code block execution exceeded 10 seconds timeout
Traceback (most recent call last):
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/stopit/utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/tpot/decorators.py", line 57, in time_limited_call
    func(*args)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/pipeline.py", line 335, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/core.py", line 436, in inner_f
    return f(**kwargs)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/sklearn.py", line 1187, in fit
    callbacks=callbacks,
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/training.py", line 197, in train
    early_stopping_rounds=early_stopping_rounds)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/training.py", line 81, in _train_internal
    bst.update(dtrain, i, obj)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/core.py", line 1501, in update
    dtrain.handle))
stopit.utils.TimeoutException
2023-01-22 18:56:25,359 - utils.py - Code block execution exceeded 10 seconds timeout
Traceback (most recent call last):
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/stopit/utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/tpot/decorators.py", line 57, in time_limited_call
    func(*args)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/pipeline.py", line 335, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/core.py", line 436, in inner_f
    return f(**kwargs)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/sklearn.py", line 1187, in fit
    callbacks=callbacks,
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/training.py", line 197, in train
    early_stopping_rounds=early_stopping_rounds)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/training.py", line 81, in _train_internal
    bst.update(dtrain, i, obj)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/xgboost/core.py", line 1501, in update
    dtrain.handle))
stopit.utils.TimeoutException
